### ISSUE TITLE
flux:field.inline.fal multilanguage handling broken in TYPO3 10

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1810]
Using a flux:field.inline.fal field in TYPO3 10.4.5 and flux current origin/development branch has a roblem:
 
When translating a flux based content element with a flux:field.inline.fal field, the file references in there don't get translated into the translated content element. They get created in the flux fal field of the original language content element and stay in the default language. So you got all images twice in the default language content element after translating.

Field code:
```html
<flux:field.inline.fal name="teaserImages" label="Teasers" minItems="0" maxItems="99" collapseAll="TRUE" />
```

language site config:
```yaml
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de
    direction: ''
    flag: de
    languageId: '0'
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: gb
    languageId: '2'
```

Any hints? flux bug? core bug?
