### ISSUE TITLE
Extending AbstractFluxController throws ServiceNotFoundException

### ISSUE THREAD

**Issue by medienintegration** [FluidTYPO3/flux#2000]
Due to missing dependency injection configuration a custom controller which extends the AbstractFluxController leads to a ServiceNotFoundException.

The necessary (default) configuration in Services.yaml could look like this:

```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FluidTYPO3\Flux\:
    resource: '../Classes/*'

  FluidTYPO3\Flux\Integration\Event\AfterLocalizationControllerColumnsEventListener:
    tags:
      - name: event.listener
        identifier: 'flux-after-localization-controller-columns'
        method: 'modifyColumnsManifest'
        event: TYPO3\CMS\Backend\Controller\Event\AfterPageColumnsSelectedForLocalizationEvent
```
