### ISSUE TITLE
Backend stylesheet fixes

### ISSUE THREAD

**Issue by idleworks** [FluidTYPO3/flux#460]
On mouseover content elements in page module there is some weird jumping. I tried to debug this behavoir and found out that the .toogle-content element is causing this bug.
If you drop this element in firebug, everything works fine.

``` css
.toggle-content {display: none !important;}
```

On the other hand there is a huge padding for .fce-header which leads to much space consumption.

``` css
td.t3-page-column.t3-gridCell .t3-page-colHeader {
padding-top: 36px;
}
```

I would suggest setting this to zero.
