### ISSUE TITLE
Improve flux-grid with many elements

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/flux#574]
For example i want one row with a lot of col elements or a accordion with a lot of content.

Current situation screenshot
![alt](http://i.imgur.com/iDJRbze.png)

I think it should break. In a row element its easy because you have a width style in BE (most setups).

Right now i added a view CSS properties for testing would could be possible:

``` css
.flux-grid td {
        box-sizing: border-box; /* IE8+ and browser prefixes exists */
        display: inline-block;
        margin-left: -4px;
        padding-left: 4px;
}
@media (max-width: 750px) {
    .flux-grid td {
            min-width: 50%;
    }
}
@media (max-width: 450px) {
    .flux-grid td {
            min-width: 100%;
    }
}
```

With applied CSS screenshot
![alt](http://i.imgur.com/xAcQbhC.png)
![alt](http://i.imgur.com/1cLnibk.png)
![alt](http://i.imgur.com/4WsZedU.png)
